set_attribute -type boolean [get_pins padsInst/aclkPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dcoEnablePad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/cpu_enPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/scan_enablePad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_15__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_14__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_13__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_12__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_11__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_10__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_9__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_8__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_7__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_6__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_5__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_4__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_3__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_2__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_doutPad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_15__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_14__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_13__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_12__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_11__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_10__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_9__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_8__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_7__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_6__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_5__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_4__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_3__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_2__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_doutPad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_wePad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_wePad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_15__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_14__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_13__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_12__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_11__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_10__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_9__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_8__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_7__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_6__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_5__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_4__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_3__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_2__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_dinPad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_14__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_13__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_12__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_11__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_10__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_9__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_8__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_7__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_6__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_5__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_4__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_3__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_2__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_addrPad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_13__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_12__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_11__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_10__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_9__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_8__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_7__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_6__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_5__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_4__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_3__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_2__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irqPad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_15__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_14__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_13__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_12__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_11__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_10__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_9__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_8__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_7__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_6__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_5__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_4__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_3__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_2__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_1__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_doutPad/genblk_InPadv_0__inpad_Inst/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/lfxtClkPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dcoClkPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/wkupPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/scan_modePad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/reset_nPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/nmiPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_wkupPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_priorityPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_enPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dbg_uart_rxdPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dbg_enPad/padIn/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_wenPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_wenPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_15__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_14__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_13__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_12__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_11__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_dinPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_addrPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_wePad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_wePad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_15__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_14__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_13__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_12__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_11__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_dinPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_13__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_12__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_11__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/per_addrPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_15__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_14__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_13__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_12__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_11__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_doutPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_13__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_12__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_11__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/irq_accPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_wenPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_wenPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_15__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_14__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_13__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_12__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_11__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_10__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_9__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemdinPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_8__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_7__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_6__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_5__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_4__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_3__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_2__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_1__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmemAddrPad/genblk_OutPadv_0__outpad_Inst/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/smclkPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/puc_rstPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/pmem_cenPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_respPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dma_readyPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/mclkPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/lfxt_wkupPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/lfxt_enablePad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dmem_cen_Pad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dco_wkupPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dbg_i2c_sda_outPad/f12_padOut/PAD] is_pad true
set_attribute -type boolean [get_pins padsInst/dbgFreezePad/f12_padOut/PAD] is_pad true
